var StringResource = {
    en: {
        "HowToPlay_1": "Sliding finger across the screen moves your character.",
        "HowToPlay_2": "Automatically shot is fired.",
        "HowToPlay_3": "Getting near an enemy shot increase the Chicken gauge.",
        "HowToPlay_4": "When the Chicken gauge is charged, chicks come to help.",
        "HowToPlay_5": "When push the Shield button, chicks wear an egg and reflect enemy shot.",
        "HowToPlay_6": "While push the Shield button, the Chiken gauge is decreased.",
        "HowToPlay_Controller_1": "Using the left analog stick moves your character.",
        "HowToPlay_Controller_2": "Automatically shot is fired.",
        "HowToPlay_Controller_3": "Getting near an enemy shot increase the Chicken gauge.",
        "HowToPlay_Controller_4": "When the Chicken gauge is charged, chicks come to help.",
        "HowToPlay_Controller_5": "When push A button, chicks wear an egg and reflect enemy shot.",
        "HowToPlay_Controller_6": "While push A button, the Chiken gauge is decreased.",
        "Tweet1stLoop": "Toritoma, Go on to stage %d. Earned %d points the score. #toritoma",
        "Tweet2ndLoop": "Toritoma, Go on to stage %d in %d%s lap. Earned %d points the score. #toritoma",
        "CreditName_1": "Production\n    Kaneda",
        "CreditName_2": "BGM\n    Maou Damashii",
        "CreditName_3": "Jingle\n    YouFulca",
        "CreditName_4": "Sound Effect\n    Skipmore",
        "CreditName_5": "Font\n    Misaki Font",
        "CreditName_6": "Font\n    Noto Fonts",
        "CreditLink_1": "http://blog.monochrome-soft.com/",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://www.geocities.jp/littlimi/misaki.htm",
        "CreditLink_6": "https://www.google.com/get/noto/",
        "StoreMessage": "・Remove ads.\n・Unlock 2nd lap after the game clear.",
        "StorePurchased": "PURCHASED",
    },
    ja: {
        "HowToPlay_1": "画面をスライドすると自機が移動します。",
        "HowToPlay_2": "自動的にショットが発射されます。",
        "HowToPlay_3": "敵の弾に近づくとチキンゲージが溜まります。",
        "HowToPlay_4": "チキンゲージが溜まるとヒヨコが助けにきます。",
        "HowToPlay_5": "シールドボタンを押すとヒヨコが卵をかぶって敵の弾を跳ね返します。",
        "HowToPlay_6": "シールドボタンを押している間はチキンゲージが減っていきます。",
        "HowToPlay_Controller_1": "左スティックを傾けると自機が移動します。",
        "HowToPlay_Controller_2": "自動的にショットが発射されます。",
        "HowToPlay_Controller_3": "敵の弾に近づくとチキンゲージが溜まります。",
        "HowToPlay_Controller_4": "チキンゲージが溜まるとヒヨコが助けにきます。",
        "HowToPlay_Controller_5": "Aボタンを押すとヒヨコが卵をかぶって敵の弾を跳ね返します。",
        "HowToPlay_Controller_6": "Aボタンを押している間はチキンゲージが減っていきます。",
        "Tweet1stLoop": "とりとま、ステージ%dまで進めてスコアを%d点獲得しました。 #toritoma",
        "Tweet2ndLoop": "とりとま、%d周目ステージ%dまで進めてスコアを%d点獲得しました。 #toritoma",
        "CreditName_1": "製作\n    金田",
        "CreditName_2": "BGM\n    魔王魂",
        "CreditName_3": "ジングル\n    ユーフルカ",
        "CreditName_4": "効果音\n    スキップモア",
        "CreditName_5": "フォント\n    美咲フォント",
        "CreditName_6": "フォント\n    Noto Fonts",
        "CreditLink_1": "http://blog.monochrome-soft.com/",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://www.geocities.jp/littlimi/misaki.htm",
        "CreditLink_6": "https://www.google.com/get/noto/",
        "StoreMessage": "・広告の削除\n・2周目モードの解除",
        "StorePurchased": "購入済み",
    },
    zh: {
        "HowToPlay_1": "滑动指头在画面上就你的角色动。",
        "HowToPlay_2": "子弹自动被开。",
        "HowToPlay_3": "擦敌的子弹就鸡计堆积。",
        "HowToPlay_4": "当鸡计堆积，雏鸡来帮助。",
        "HowToPlay_5": "当按盾钮，雏鸡戴蛋壳，弹回敌的子弹。",
        "HowToPlay_6": "当按盾钮，鸡计减少。",
        "HowToPlay_Controller_1": "推左摇杆就你的角色动。",
        "HowToPlay_Controller_2": "子弹自动被开。",
        "HowToPlay_Controller_3": "擦敌的子弹就鸡计堆积。",
        "HowToPlay_Controller_4": "当鸡计堆积，雏鸡来帮助。",
        "HowToPlay_Controller_5": "当按A钮，雏鸡戴蛋壳，弹回敌的子弹。",
        "HowToPlay_Controller_6": "当按A钮，鸡计减少。",
        "Tweet1stLoop": "鸡射，到达第%d阶段。获得%d分。 #toritoma",
        "Tweet2ndLoop": "鸡射，到达第%d循环的第%d阶段。获得%d分。 #toritoma",
        "CreditName_1": "制作\n    金田",
        "CreditName_2": "背景音乐\n    魔王魂",
        "CreditName_3": "静乐县\n    YouFulca",
        "CreditName_4": "音效\n    Skipmore",
        "CreditName_5": "字体\n    美咲字体",
        "CreditName_6": "字体\n    Noto Fonts",
        "CreditLink_1": "http://blog.monochrome-soft.com/",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://www.geocities.jp/littlimi/misaki.htm",
        "CreditLink_6": "https://www.google.com/get/noto/",
        "StoreMessage": "・排除广告。\n・解锁过关后的第二循环。",
        "StorePurchased": "购买了",
    },
    ko: {
        "HowToPlay_1": "화면을 슬라이드하면 자신의 캐릭터가 이동합니다.",
        "HowToPlay_2": "자동으로 샷이 발사됩니다.",
        "HowToPlay_3": "적의 총알에 가까워지면 치킨 게이지가 쌓입니다.",
        "HowToPlay_4": "치킨 게이지가 쌓이면 병아리가 도와주러 합니다.",
        "HowToPlay_5": "방패 버튼을 누르면 병아리가 달걀을 쓰고 적의 총알을 반사합니다.",
        "HowToPlay_6": "방패 버튼을 누르고있는 동안은 치킨 게이지가 줄어 듭니다.",
        "HowToPlay_Controller_1": "왼쪽 스틱을 기울이면 자신의 캐릭터가 이동합니다.",
        "HowToPlay_Controller_2": "자동으로 샷이 발사됩니다.",
        "HowToPlay_Controller_3": "적의 총알에 가까워지면 치킨 게이지가 쌓입니다.",
        "HowToPlay_Controller_4": "치킨 게이지가 쌓이면 병아리가 도와주러 합니다.",
        "HowToPlay_Controller_5": "A 버튼을 누르면 병아리가 달걀을 쓰고 적의 총알을 반사합니다.",
        "HowToPlay_Controller_6": "A 버튼을 누르고있는 동안은 치킨 게이지가 줄어 듭니다.",
        "Tweet1stLoop": "토리토마, %d 단계까지 진행하고 점수를 %d 점 획득했습니다. #toritoma",
        "Tweet2ndLoop": "토리토마, %d 회차 %d 단계까지 진행하고 점수를 %d 점 획득했습니다. #toritoma",
        "CreditName_1": "제작\n    카네다",
        "CreditName_2": "BGM\n    마왕 영혼",
        "CreditName_3": "징글\n    유후루카",
        "CreditName_4": "효과음\n    스킵 모어",
        "CreditName_5": "글꼴\n    미사키 글꼴",
        "CreditName_6": "글꼴\n    Noto Fonts",
        "CreditLink_1": "http://blog.monochrome-soft.com/",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://www.geocities.jp/littlimi/misaki.htm",
        "CreditLink_6": "https://www.google.com/get/noto/",
        "StoreMessage": "・광고 삭제\n・2 회차 모드 해제",
        "StorePurchased": "구입 완료",
    },
};
export default StringResource;
