var StringResource = {
    en: {
        "HowToPlay_touch_1": "Sliding finger across the screen moves your character.",
        "HowToPlay_touch_2": "Automatically shot is fired.",
        "HowToPlay_touch_3": "Getting near an enemy shot increase the Chicken gauge.",
        "HowToPlay_touch_4": "When the Chicken gauge is charged, chicks come to help.",
        "HowToPlay_touch_5": "When push the Shield button, chicks wear an egg and reflect enemy shot.",
        "HowToPlay_touch_6": "While push the Shield button, the Chiken gauge is decreased.",
        "HowToPlay_gamepad_1": "Using the left analog stick moves your character.",
        "HowToPlay_gamepad_2": "Automatically shot is fired.",
        "HowToPlay_gamepad_3": "Getting near an enemy shot increase the Chicken gauge.",
        "HowToPlay_gamepad_4": "When the Chicken gauge is charged, chicks come to help.",
        "HowToPlay_gamepad_5": "When push A button, chicks wear an egg and reflect enemy shot.",
        "HowToPlay_gamepad_6": "While push A button, the Chiken gauge is decreased.",
        "HowToPlay_keyboard_1": "Pressing cursor keys moves your character.",
        "HowToPlay_keyboard_2": "Automatically shot is fired.",
        "HowToPlay_keyboard_3": "Getting near an enemy shot increase the Chicken gauge.",
        "HowToPlay_keyboard_4": "When the Chicken gauge is charged, chicks come to help.",
        "HowToPlay_keyboard_5": "When press Z key, chicks wear an egg and reflect enemy shot.",
        "HowToPlay_keyboard_6": "While press Z key, the Chiken gauge is decreased.",
        "CreditName_1": "Production\n    A.Kaneda",
        "CreditName_2": "BGM\n    Maou Damashii",
        "CreditName_3": "Jingle\n    YouFulca",
        "CreditName_4": "Sound Effect\n    Skipmore",
        "CreditName_5": "Game Engine\n    phina.js",
        "CreditName_6": "Font\n    Noto Fonts",
        "CreditLink_1": "http://www.monochromesoft.com/dokuwiki/start",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://phinajs.com/",
        "CreditLink_6": "https://www.google.com/get/noto/",
    },
    ja: {
        "HowToPlay_touch_1": "画面をスライドすると自機が移動します。",
        "HowToPlay_touch_2": "自動的にショットが発射されます。",
        "HowToPlay_touch_3": "敵の弾に近づくとチキンゲージが溜まります。",
        "HowToPlay_touch_4": "チキンゲージが溜まるとヒヨコが助けにきます。",
        "HowToPlay_touch_5": "シールドボタンを押すとヒヨコが卵をかぶって敵の弾を跳ね返します。",
        "HowToPlay_touch_6": "シールドボタンを押している間はチキンゲージが減っていきます。",
        "HowToPlay_gamepad_1": "左スティックを傾けると自機が移動します。",
        "HowToPlay_gamepad_2": "自動的にショットが発射されます。",
        "HowToPlay_gamepad_3": "敵の弾に近づくとチキンゲージが溜まります。",
        "HowToPlay_gamepad_4": "チキンゲージが溜まるとヒヨコが助けにきます。",
        "HowToPlay_gamepad_5": "Aボタンを押すとヒヨコが卵をかぶって敵の弾を跳ね返します。",
        "HowToPlay_gamepad_6": "Aボタンを押している間はチキンゲージが減っていきます。",
        "HowToPlay_keyboard_1": "カーソルキーで自機が移動します。",
        "HowToPlay_keyboard_2": "自動的にショットが発射されます。",
        "HowToPlay_keyboard_3": "敵の弾に近づくとチキンゲージが溜まります。",
        "HowToPlay_keyboard_4": "チキンゲージが溜まるとヒヨコが助けにきます。",
        "HowToPlay_keyboard_5": "Zキーを押すとヒヨコが卵をかぶって敵の弾を跳ね返します。",
        "HowToPlay_keyboard_6": "Zキーを押している間はチキンゲージが減っていきます。",
        "CreditName_1": "Production\n    A.Kaneda",
        "CreditName_2": "BGM\n    魔王魂",
        "CreditName_3": "Jingle\n    ユーフルカ",
        "CreditName_4": "Sound Effect\n    Skipmore",
        "CreditName_5": "Game Engine\n    phina.js",
        "CreditName_6": "Font\n    Notoフォント",
        "CreditLink_1": "http://www.monochromesoft.com/dokuwiki/start",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://phinajs.com/",
        "CreditLink_6": "https://www.google.com/get/noto/",
    },
    zh: {
        "HowToPlay_touch_1": "滑动指头在画面上就你的角色动。",
        "HowToPlay_touch_2": "子弹自动被开。",
        "HowToPlay_touch_3": "擦敌的子弹就鸡计堆积。",
        "HowToPlay_touch_4": "当鸡计堆积，雏鸡来帮助。",
        "HowToPlay_touch_5": "当按盾钮，雏鸡戴蛋壳，弹回敌的子弹。",
        "HowToPlay_touch_6": "当按盾钮，鸡计减少。",
        "HowToPlay_gamepad_1": "推左摇杆就你的角色动。",
        "HowToPlay_gamepad_2": "子弹自动被开。",
        "HowToPlay_gamepad_3": "擦敌的子弹就鸡计堆积。",
        "HowToPlay_gamepad_4": "当鸡计堆积，雏鸡来帮助。",
        "HowToPlay_gamepad_5": "当按A钮，雏鸡戴蛋壳，弹回敌的子弹。",
        "HowToPlay_gamepad_6": "当按A钮，鸡计减少。",
        "HowToPlay_keyboard_1": "按光标键就你的角色动。",
        "HowToPlay_keyboard_2": "子弹自动被开。",
        "HowToPlay_keyboard_3": "擦敌的子弹就鸡计堆积。",
        "HowToPlay_keyboard_4": "当鸡计堆积，雏鸡来帮助。",
        "HowToPlay_keyboard_5": "当按下Z键时，雏鸡戴蛋壳，弹回敌的子弹。",
        "HowToPlay_keyboard_6": "当按下Z键时，鸡计减少。",
        "CreditName_1": "Production\n    A.Kaneda",
        "CreditName_2": "BGM\n    Maou Damashii",
        "CreditName_3": "Jingle\n    YouFulca",
        "CreditName_4": "Sound Effect\n    Skipmore",
        "CreditName_5": "Game Engine\n    phina.js",
        "CreditName_6": "Font\n    Noto Fonts",
        "CreditLink_1": "http://www.monochromesoft.com/dokuwiki/start",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://phinajs.com/",
        "CreditLink_6": "https://www.google.com/get/noto/",
    },
    ko: {
        "HowToPlay_touch_1": "화면을 슬라이드하면 자신의 캐릭터가 이동합니다.",
        "HowToPlay_touch_2": "자동으로 샷이 발사됩니다.",
        "HowToPlay_touch_3": "적의 총알에 가까워지면 치킨 게이지가 쌓입니다.",
        "HowToPlay_touch_4": "치킨 게이지가 쌓이면 병아리가 도와주러 합니다.",
        "HowToPlay_touch_5": "방패 버튼을 누르면 병아리가 달걀을 쓰고 적의 총알을 반사합니다.",
        "HowToPlay_touch_6": "방패 버튼을 누르고있는 동안은 치킨 게이지가 줄어 듭니다.",
        "HowToPlay_gamepad_1": "왼쪽 스틱을 기울이면 자신의 캐릭터가 이동합니다.",
        "HowToPlay_gamepad_2": "자동으로 샷이 발사됩니다.",
        "HowToPlay_gamepad_3": "적의 총알에 가까워지면 치킨 게이지가 쌓입니다.",
        "HowToPlay_gamepad_4": "치킨 게이지가 쌓이면 병아리가 도와주러 합니다.",
        "HowToPlay_gamepad_5": "A 버튼을 누르면 병아리가 달걀을 쓰고 적의 총알을 반사합니다.",
        "HowToPlay_gamepad_6": "A 버튼을 누르고있는 동안은 치킨 게이지가 줄어 듭니다.",
        "HowToPlay_keyboard_1": "커서 키로 자신의 캐릭터가 이동합니다.",
        "HowToPlay_keyboard_2": "자동으로 샷이 발사됩니다.",
        "HowToPlay_keyboard_3": "적의 총알에 가까워지면 치킨 게이지가 쌓입니다.",
        "HowToPlay_keyboard_4": "치킨 게이지가 쌓이면 병아리가 도와주러 합니다.",
        "HowToPlay_keyboard_5": "Z 키를 누르면 병아리가 달걀을 쓰고 적의 총알을 반사합니다.",
        "HowToPlay_keyboard_6": "Z 키를 누르고있는 동안은 치킨 게이지가 줄어 듭니다.",
        "CreditName_1": "Production\n    A.Kaneda",
        "CreditName_2": "BGM\n    Maou Damashii",
        "CreditName_3": "Jingle\n    YouFulca",
        "CreditName_4": "Sound Effect\n    Skipmore",
        "CreditName_5": "Game Engine\n    phina.js",
        "CreditName_6": "Font\n    Noto Fonts",
        "CreditLink_1": "http://www.monochromesoft.com/dokuwiki/start",
        "CreditLink_2": "http://maoudamashii.jokersounds.com/",
        "CreditLink_3": "http://wingless-seraph.net/",
        "CreditLink_4": "http://www.skipmore.com/app/",
        "CreditLink_5": "http://phinajs.com/",
        "CreditLink_6": "https://www.google.com/get/noto/",
    },
};
export default StringResource;
